### ISSUE TITLE
How do you insert unescaped HTML? 

### ISSUE THREAD

**Issue by timuster** [nebrelbug/squirrelly.js.org#6]
Is it possible to insert html tags (< br >, < p >, etc.) with Squirrelly? In other words, I'd like to insert "Hello! < br > my name is < h4 >Foo</ h4 >" in the template, with the HTML tags being rendered as such (instead of being parsed as plain text).

**Comment by bgub** [comment]
Hi @timuster, thanks for the question!

You sure can! If your options are:

```js
{
  htmlstuff: "<script>alert('malicious XSS')</script>"
}
```

In your template, you can write `{{htmlstuff | safe}}` instead of `{{htmlstuff}}`

The `safe` filter tells Squirrelly to trust the HTML you pass in (it converts it to text by default, to prevent against malicious scripts or other XSS that could be in the data if users created the data).
